### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by josejulioramos**
Removed system development code from subsystem repository

### CODE REVIEW

**Review by rconway — COMMENTED** [review]
Seem to have removed a lot of stuff from the travis file - what is the reason for this ?

**Comment by josejulioramos** [comment]
That stuff is now in the EOEPCA "system-level" repository. Remember that we decided on separating the subsystem and system code.

**Comment by rconway** [comment]
> That stuff is now in the EOEPCA "system-level" repository. Remember that we decided on separating the subsystem and system code.

OK, understood

**Comment by josejulioramos** [comment]
Merged after 1 review... just to end the reminders.

**Pull request merged**
